-- Chạy sau db/supabase.sql trong Supabase SQL Editor.
begin;
insert into projects (id, name, slug, location, status, cover, summary, description, featured) values ('ocean-park-2-3', 'Vinhomes Ocean Park 2 & 3', 'vinhomes-ocean-park-2-3', 'Văn Giang, Hưng Yên', 'Đang tư vấn', 'vinhomes-ocean-park-1-2-3.jpg', 'Đô thị biển phía Đông Hà Nội dành cho nhu cầu ở thực và đầu tư dài hạn.', 'Tổng hợp thông tin sản phẩm, chính sách và lựa chọn phù hợp tại Ocean Park 2 & 3.', true) on conflict (id) do update set name=excluded.name, slug=excluded.slug, location=excluded.location, status=excluded.status, cover=excluded.cover, summary=excluded.summary, description=excluded.description, featured=excluded.featured;
insert into units (id, project_id, code, type, area, price, status, note) values ('op23-can-lien-ke-01', 'ocean-park-2-3', 'OP23-LK-01', 'Liền kề', '90 m²', 'Liên hệ', 'Đang bán', '') on conflict (id) do update set project_id=excluded.project_id, code=excluded.code, type=excluded.type, area=excluded.area, price=excluded.price, status=excluded.status, note=excluded.note;
insert into projects (id, name, slug, location, status, cover, summary, description, featured) values ('ha-long-xanh', 'Vinhomes Hạ Long Xanh – Global Gate', 'ha-long-xanh', 'Tuần Châu & Quảng Yên, Quảng Ninh', 'Nhận đăng ký quan tâm', 'ha_long_xanh.jpg', 'Tổ hợp ven biển kết nối du lịch, đô thị và hạ tầng vùng Đông Bắc.', 'Cập nhật giỏ hàng, vị trí và thông tin mở bán theo từng giai đoạn.', true) on conflict (id) do update set name=excluded.name, slug=excluded.slug, location=excluded.location, status=excluded.status, cover=excluded.cover, summary=excluded.summary, description=excluded.description, featured=excluded.featured;
insert into projects (id, name, slug, location, status, cover, summary, description, featured) values ('hai-van-bay', 'Vinhomes Hải Vân Bay', 'hai-van-bay', 'Làng Vân, Đà Nẵng', 'Đang cập nhật', 'hai_van_bay.jpg', 'Góc nhìn về sản phẩm nghỉ dưỡng và tiềm năng phát triển phía Bắc Đà Nẵng.', 'Đăng tải thông tin dự án, chính sách và căn phù hợp nhu cầu nghỉ dưỡng.', false) on conflict (id) do update set name=excluded.name, slug=excluded.slug, location=excluded.location, status=excluded.status, cover=excluded.cover, summary=excluded.summary, description=excluded.description, featured=excluded.featured;
insert into projects (id, name, slug, location, status, cover, summary, description, featured) values ('can-gio', 'Vinhomes Green Paradise – Cần Giờ', 'can-gio-green-paradise', 'Cần Giờ, TP. Hồ Chí Minh', 'Đang cập nhật', 'vin_cangio.jpg', 'Đô thị biển và câu chuyện hạ tầng kết nối phía Nam.', 'Theo dõi thông tin quy hoạch, tiến độ và sản phẩm theo từng đợt.', false) on conflict (id) do update set name=excluded.name, slug=excluded.slug, location=excluded.location, status=excluded.status, cover=excluded.cover, summary=excluded.summary, description=excluded.description, featured=excluded.featured;
insert into projects (id, name, slug, location, status, cover, summary, description, featured) values ('sai-gon-park', 'Vinhomes Sài Gòn Park', 'sai-gon-park', 'Hóc Môn, TP. Hồ Chí Minh', 'Nhận nhu cầu', 'sai_gon_park.jpg', 'Cập nhật thông tin quy hoạch, tiến độ và sản phẩm phía Tây Bắc thành phố.', 'Tư vấn lựa chọn sản phẩm dựa trên mục tiêu ở thực và đầu tư.', false) on conflict (id) do update set name=excluded.name, slug=excluded.slug, location=excluded.location, status=excluded.status, cover=excluded.cover, summary=excluded.summary, description=excluded.description, featured=excluded.featured;
insert into articles (id, title, slug, category, excerpt, content, published_at, status) values ('article-1', '5 câu hỏi nên trả lời trước khi chọn một dự án Vinhomes', '5-cau-hoi-truoc-khi-chon-du-an-vinhomes', 'Góc nhìn đầu tư', 'Đừng bắt đầu bằng câu hỏi giá bao nhiêu. Hãy bắt đầu bằng việc sản phẩm có phù hợp với mục tiêu và thời gian của bạn hay không.', '', '2026-10-06', 'published') on conflict (id) do update set title=excluded.title, slug=excluded.slug, category=excluded.category, excerpt=excluded.excerpt, content=excluded.content, published_at=excluded.published_at, status=excluded.status;
insert into articles (id, title, slug, category, excerpt, content, published_at, status) values ('article-2', 'Mua để ở và mua để đầu tư: cách lọc sản phẩm khác nhau thế nào?', 'mua-de-o-va-mua-de-dau-tu', 'Kinh nghiệm', 'Cùng một dự án nhưng tiêu chí chọn căn, vị trí và dòng tiền có thể hoàn toàn khác nhau.', '', '2026-10-05', 'published') on conflict (id) do update set title=excluded.title, slug=excluded.slug, category=excluded.category, excerpt=excluded.excerpt, content=excluded.content, published_at=excluded.published_at, status=excluded.status;
insert into site_settings(key,value) values ('public', '{"brand": "Huệ Tây Vinhomes", "hotline": "0825684139", "zalo": "https://zalo.me/0825684139", "facebook": "https://www.facebook.com/haihau.le.7"}'::jsonb) on conflict (key) do update set value=excluded.value;
commit;
